# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Kactus
    url: https://www.kactus.com
  - name: Bird Office
    url: https://www.bird-office.com
    
status-website:
  baseUrl: /uptime # where "repo" is your repository name
  logoUrl: https://www.kactus.com/assets/logos/kactus/only-logo-49339dc1e6ddaaaf34089190d4430e5532d132017d25c6f2a4e19a793648b5b9.png
  name: BOK Uptime
  introTitle: Our Status page
  introMessage: System status
  navbar:
    - title: Status
      href: /
    - title: Kactus
      href: https://www.kactus.com
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
